#!/bin/bash

python profile-class-gen.py -i af > AF.java
python profile-class-gen.py -i an > AN.java
python profile-class-gen.py -i ar > AR.java
python profile-class-gen.py -i ast > AST.java
python profile-class-gen.py -i be > BE.java
python profile-class-gen.py -i bg > BG.java
python profile-class-gen.py -i bn > BN.java
python profile-class-gen.py -i br > BR.java
python profile-class-gen.py -i ca > CA.java
python profile-class-gen.py -i cs > CS.java
python profile-class-gen.py -i cy > CY.java
python profile-class-gen.py -i da > DA.java
python profile-class-gen.py -i de > DE.java
python profile-class-gen.py -i el > EL.java
python profile-class-gen.py -i en > EN.java
python profile-class-gen.py -i es > ES.java
python profile-class-gen.py -i et > ET.java
python profile-class-gen.py -i eu > EU.java
python profile-class-gen.py -i fa > FA.java
python profile-class-gen.py -i fi > FI.java
python profile-class-gen.py -i fr > FR.java
python profile-class-gen.py -i gl > GL.java
python profile-class-gen.py -i gu > GU.java
python profile-class-gen.py -i he > HE.java
python profile-class-gen.py -i hi > HI.java
python profile-class-gen.py -i hr > HR.java
python profile-class-gen.py -i ht > HT.java
python profile-class-gen.py -i hu > HU.java
python profile-class-gen.py -i ga > GA.java
python profile-class-gen.py -i id > ID.java
python profile-class-gen.py -i is > IS.java
python profile-class-gen.py -i it > IT.java
python profile-class-gen.py -i ja > JA.java
python profile-class-gen.py -i kn > KN.java
python profile-class-gen.py -i ko > KO.java
python profile-class-gen.py -i lt > LT.java
python profile-class-gen.py -i lv > LV.java
python profile-class-gen.py -i mk > MK.java
python profile-class-gen.py -i ml > ML.java
python profile-class-gen.py -i mr > MR.java
python profile-class-gen.py -i ms > MS.java
python profile-class-gen.py -i mt > MT.java
python profile-class-gen.py -i ne > NE.java
python profile-class-gen.py -i nl > NL.java
python profile-class-gen.py -i no > NO.java
python profile-class-gen.py -i oc > OC.java
python profile-class-gen.py -i pa > PA.java
python profile-class-gen.py -i pl > PL.java
python profile-class-gen.py -i pt > PT.java
python profile-class-gen.py -i ro > RO.java
python profile-class-gen.py -i ru > RU.java
python profile-class-gen.py -i sk > SK.java
python profile-class-gen.py -i sl > SL.java
python profile-class-gen.py -i so > SO.java
python profile-class-gen.py -i sq > SQ.java
python profile-class-gen.py -i sr > SR.java
python profile-class-gen.py -i sv > SV.java
python profile-class-gen.py -i sw > SW.java
python profile-class-gen.py -i ta > TA.java
python profile-class-gen.py -i te > TE.java
python profile-class-gen.py -i th > TH.java
python profile-class-gen.py -i tl > TL.java
python profile-class-gen.py -i tr > TR.java
python profile-class-gen.py -i uk > UK.java
python profile-class-gen.py -i ur > UR.java
python profile-class-gen.py -i vi > VI.java
python profile-class-gen.py -i yi > YI.java
python profile-class-gen.py -i zh-cn > ZH-CN.java
python profile-class-gen.py -i zh-tw > ZH-TW.java

